version: "3"

services:
  mongo:
    image: mongo
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=plant-tracker-api
      - MONGO_INITDB_ROOT_PASSWORD=s3cr3tPssWdrD

  api:
    build: ./api
    volumes:
      - "./api/build:/var/www"
    ports:
      - "9000:9000"
    links:
      - mongo
    environment:
      - URL_MONGO=mongodb://plant-tracker-api:s3cr3tPssWdrD@mongo
